---
title: "Math Camp Calculus Day 2: Solutions for Selected Exercises"
output:
  xaringan::moon_reader:
    lib_dir: libs
    #mathjax: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-MML-AM_CHTML"
    css: xaringan-themer.css
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Optimization

Find the local minimum and local maximum of the function below, and check mathematically which is the minimum and which is the maximum:

$x^3-x^2+1$

To find local minima and maxima, find the first derivative:

\begin{align}
f'(x) = (x^3−x^2+1)' = 3x^2 − 2x
\end{align}

...then set it to 0 and solve for $x$:

\begin{align}
3x^2 − 2x = 0 \\
x(3x - 2) = 0   
\end{align}

which means $x = 0$ 

or 

$3x - 2 = 0 \implies x = \frac{2}{3}$ 

So $x = 0$ and $x = \frac{2}{3}$ are local minima or maxima

---

## Optimization (continued)

To check which is the maximum and which is the minimum, find the second derivative:

\begin{align}
f''(x) = (3x^2 − 2x)' = 6x - 2
\end{align}

...and then plug in the $x$ values where we suspect the maxima or minima to be:

$f''(0) = 6 \cdot 0 - 2 = -2 \implies$ a local maximum, because $f''x() < 0$

$f''(\frac{2}{3}) = 6 \cdot \frac{2}{3} - 2 = 2 \implies$ a local minimum, because $f''x() > 0$ 

---

## Partial derivatives

Find the partial derivatives of the function below with respect to each variable

$g(p,q) = 8p^2q + 4pq − 7pq^2 + 18$

First, the partial derivative with respect to $p$:

\begin{align}
\frac{\partial[f(p,q)]}{\partial p} = 16pq + 4q - 7q^2
\end{align}

Now, the partial derivative with respect to $q$:

\begin{align}
\frac{\partial[f(p,q)]}{\partial q} = 8p^2 + 4p - 14pq
\end{align}

---

## Partial higher-order derivatives

Consider again $f(x, y) = 3x^3y^2$. Find:

- $\frac{\partial^3}{\partial x^2 \partial y}$
- $\frac{\partial^3}{\partial x \partial y^2}$

\begin{align}
\frac{\partial^3}{\partial x^2 \partial y}(3x^3y^2) &= \frac{\partial^2}{\partial x^2}(2 \cdot 3x^3 y^{2-1}) \\
&= \frac{\partial^2}{\partial x^2}(6x^3 y) \\
&=\frac{\partial}{\partial x}(3 \cdot 6x^{3-1} y) \\
&=\frac{\partial}{\partial x}(18x^2 y) \\
&=2 \cdot 18x y \\
&=36xy
\end{align}

---

## Partial higher-order derivatives (cont.)

\begin{align}
\frac{\partial^3}{\partial x \partial y^2}(3x^3y^2) &= \frac{\partial^2}{\partial x \partial y}(2 \cdot 3x^3 y^{2-1}) \\
&= \frac{\partial^2}{\partial x \partial y}(6x^3 y) \\
&= \frac{\partial}{\partial x}(6x^3 y^{1-1}) \\
&= \frac{\partial}{\partial x}(6x^3) \\
&= 3 \cdot 6x^{3-1} \\
&= 18x^2
\end{align}

---

## Integrals

Find the indefinite integral of the function below, and calculate the area under the curve between 0 and 1:

$\int (2x^3-3x^2+7x+4)dx$

First, let's find the indefinite integral by taking an antiderivative of this function:

\begin{align}
\int  (2x^3-3x^2+7x+4)  &=  \int 2x^3 dx - \int 3x^2 dx + \int 7x + \int 4  \\
&= 2 \int x^3 dx - 3 \int x^2 dx + 7 \int x + \int 4\\
&= \frac{2}{3+1} x^{3+1} - \frac{3}{2+1} x^{2+1} + \frac{7}{1+1} x^{1+1} + 4 x + C\\
&= \frac{1}{2} x^4 - x^3 + \frac{7}{2} x^2 + 4 x + C\\
\end{align}

---

## Integrals (cont.)

Now, let's substitute $x=0$ and $x=1$ to find the area between 0 and 1:

\begin{align}
\int_0^1  (2x^3-3x^2+7x+4)dx    &= \frac{1}{2} x^4 - x^3 + \frac{7}{2} x^2 + 4 x\displaystyle\rvert_0^1  \\
&= (\frac{1}{2} \cdot 1^4 - 1^3 + \frac{7}{2} \cdot 1^2 + 4 \cdot 1) \\
&- (\frac{1}{2} \cdot 0^4 - 0^3 + \frac{7}{2} \cdot 0^2 + 4 \cdot 0)\\
&= (\frac{1}{2} - 1 + \frac{7}{2} + 4) - (0 - 0 + 0 + 0)\\
& = 7
\end{align}